# Generated by Django 4.1.2 on 2023-01-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('wordsEnglish', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('wordsChinese', models.CharField(max_length=20)),
                ('wordsDescription', models.CharField(max_length=100)),
                ('wordsPath', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('wordsEnglish', models.CharField(max_length=20)),
                ('wordsProficiency', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('username', 'wordsEnglish')},
            },
        ),
    ]
