# Generated by Django 4.1.2 on 2023-01-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gesture', '0003_alter_userinfo_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translate',
            options={'verbose_name': '单词信息', 'verbose_name_plural': '单词信息'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': '单词熟练度信息', 'verbose_name_plural': '单词熟练度信息'},
        ),
    ]
